<a href="https://colab.research.google.com/github/kaiserkonok/deep_learning_projects_for_kids/blob/master/The_%E2%80%9COdd_One_Out%E2%80%9D_Problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from matplotlib import pyplot as plt
import keras
from keras import Sequential
from keras.layers import Dense
from keras.utils import to_categorical # Import the utility function

In [2]:
def generate_odd_one_out_data(n_samples=1000, low=0, high=10):
    X = []
    y = []

    for _ in range(n_samples):
        # Pick a common value
        common = np.random.randint(low, high)
        odd = common
        while odd == common:
            odd = np.random.randint(low, high)

        # Choose the odd index
        odd_index = np.random.randint(0, 3)
        sample = [common] * 3
        sample[odd_index] = odd

        X.append(sample)
        y.append(odd_index)

    return np.array(X), np.array(y)

In [3]:
x, y = generate_odd_one_out_data(40000)

In [4]:
x

array([[6, 6, 3],
       [3, 8, 3],
       [7, 7, 8],
       ...,
       [9, 3, 3],
       [0, 6, 0],
       [6, 1, 6]])

In [5]:
y_one_hot = to_categorical(y, num_classes=3)

In [6]:
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(3, )))
model.add(Dense(64, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(3, activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy'],
)

In [8]:
model.fit(x, y_one_hot, epochs=10, batch_size=128)

Epoch 1/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.9422 - loss: 0.3147
Epoch 2/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 1.0000 - loss: 0.0011
Epoch 3/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 1.0000 - loss: 2.2936e-04
Epoch 4/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 1.0000 - loss: 8.3775e-05
Epoch 5/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 1.0000 - loss: 4.1715e-05
Epoch 6/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 1.0000 - loss: 2.6425e-05
Epoch 7/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 1.0000 - loss: 1.7469e-05
Epoch 8/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 1.2143e-05
Epoch 9/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 1.0000 - loss: 8.6727e-06
Epoch 10/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 1.0000 - loss: 6.6612e-06


In [9]:
y

array([2, 1, 2, ..., 0, 1, 1])

In [10]:
x.shape

(40000, 3)

In [11]:
y.shape

(40000,)

In [12]:
y_one_hot.shape

(40000, 3)

In [18]:
test_data = np.array([
  [3, 3, 7],
  [4, 1, 4],
  [1, 0, 0]
])
np.argmax(model.predict(test_data), axis=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


array([2, 1, 0])